name: Build cub3d

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install -y libx11-dev libxext-dev libbsd-dev libxrandr-dev libxinerama-dev libxcursor-dev libxi-dev

      - name: Compile cub3d
        run: make

      - name: Compile bonus version
        run: make bonus

      - name: Clean build
        run: make fclean
