name: Build cub3D

on:
  push:
    branches: [ "main", "alex", "clement" ]
  pull_request:
    branches: [ "main", "alex", "clement" ]

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install -y libx11-dev libxext-dev libbsd-dev libxrandr-dev libxinerama-dev libxcursor-dev libxi-dev python3-pip
          sudo pip3 install norminette

      - name: Run norminette (fail visually, but continue)
        continue-on-error: true
        run: |
          OUTPUT=$(norminette src/ include/ libft/)
          echo "$OUTPUT"
          echo "$OUTPUT" | grep -q "Error" && exit 1 || exit 0
        
      - name: Compile cub3D
        run: make

      - name: run cub3D
        run: ./cub3D maps/map1.cub

      - name: Compile bonus version
        run: make bonus

      - name: Clean build
        run: make fclean
